CREATE_TXT(TXT_ID_O2CONSOLE,               "o2console")
CREATE_TXT(TXT_ID_FOR_MCCR,                "for mCCR")
CREATE_TXT(TXT_ID_VERSION,                 "v2.05 03.14")

CREATE_TXT(TXT_ID_SWITCH_ON,               "SWITCH ON?")
CREATE_TXT(TXT_ID_CALIBARTION_QUESTION,    "CALIBRATE")
CREATE_TXT(TXT_ID_CALIBARTION_1,           "INJECT OXYGEN:")
CREATE_TXT(TXT_ID_ENTERING_DIVEMODE,       "DIVE MODE")
CREATE_TXT(TXT_ID_YES,                     "YES")
CREATE_TXT(TXT_ID_NO,                      "NO")
CREATE_TXT(TXT_ID_OK,                      "OK")
CREATE_TXT(TXT_ID_CALIBRATE,               "CALIBRATE")
CREATE_TXT(TXT_ID_SKIP,                    "SKIP")
CREATE_TXT(TXT_ID_OXYGEN,                  "PPO2:")
CREATE_TXT(TXT_ID_PWR,                     "PWR")
CREATE_TXT(TXT_ID_SET,                     "SET")
CREATE_TXT(TXT_ID_POWER_DOWN,              "POWER DOWN")
CREATE_TXT(TXT_ID_CELLS1,                  "O2 CELLS...")
CREATE_TXT(TXT_ID_CELLS2,                  "O2 CELLS")
CREATE_TXT(TXT_ID_ARE_OK,                  "ARE OK")
CREATE_TXT(TXT_ID_CELLS3,                  "O2 CELLS?")
CREATE_TXT(TXT_ID_CHANGE,                  "CHANGE?")
CREATE_TXT(TXT_ID_HPA,                     "hPa")
CREATE_TXT(TXT_ID_DOWN,                    "DOWN")
CREATE_TXT(TXT_ID_UP,                      "UP")
CREATE_TXT(TXT_ID_ATMPRESSURE,             "ATM. PRESSURE")
CREATE_TXT(TXT_ID_SAVED,                   "SAVED")

CREATE_TXT(TXT_ID_TOGGLE,                  "TOGGLE")
CREATE_TXT(TXT_ID_ON,                      "ON")
CREATE_TXT(TXT_ID_OFF,                     "OFF")
CREATE_TXT(TXT_ID_SETTINGS,                "SETTINGS")
CREATE_TXT(TXT_ID_O2CELL,                  "o2 cell")


